name: Crunchbase dashboard Cron Workflow

on:
  schedule:
  - cron: "10/10 * * * *"

jobs:
  run-Crunchbase-python:
    runs-on: windows-latest
    steps: 
      - name: Execute Cruncbase API script
        run: |
          python **/pythonScripts/OC_Crunchbase_Queries.ipynb
        shell: python

